### PR TITLE
feat: 2021.2 Intellij Support

### PR DESCRIPTION
**Pull request by michaelbrewer**
Changes:
- Migrate org.jetbrains.intellij to 1.1.4
- Bump dependencies
- Fix some java warnings

### CODE REVIEW

**Comment by michaelbrewer** [comment]
@mvanholsteijn - i added 2021.2 support and migrated the org.jetbrains.intellij to 1.1.4

**Comment by michaelbrewer** [comment]
@mvanholsteijn  oh i see that `gradle/`, `gradlew` and `gradlew.bat` are in the `.gitignore`

**Comment by mvanholsteijn** [comment]
@michaelbrewer, thank you for the update!

**Comment by mvanholsteijn** [comment]
And published!

**Pull request merged**
