### PR TITLE
2023.1 support and other fixes

### PR DESCRIPTION
**Pull request by zfil**
Couple of fixes here:
- 2023.1 support (similar to PR #32)
- handle informational lints (inspired from non-functionning PR #30)
- fix partial highlights (previously if Highlight whole line setting was turned off, only the first character was highlighted)
- started to upgrade the code by removing calls to deprecated apis

### CODE REVIEW

**Comment by mvanholsteijn** [comment]
Thank you @zfil !

**Comment by mvanholsteijn** [comment]
Hi @zfil , the plugin no longer works with 2023.1; 

```
java.lang.Throwable: Do not use constructor injection (requestorClass=io.binx.cfnlint.plugin.CheckProjectComponent)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:78)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1041)

```

It looks a big refactor is required, and I do not have the time to fix that quickly.

**Comment by zfil** [comment]
Hi @mvanholsteijn 
Yeah this refactor is in my todo list :), I've started piece by piece ...

But anyway lets back to the issue, could you please provide me more information?

With my locally built plugin I've no issue on 2023.1 (running on macos 12 intel).
IntelliJ IDEA 2023.1 (Ultimate Edition)
Build #IU-231.8109.175, built on March 28, 2023

Could you please try with my build https://wormhole.app/04BkY#stFA23PTHhAmD15No00prQ
The link will expire in 24h

**Comment by mvanholsteijn** [comment]
Hi Philippe, the error was reported by the JetBrains plugin marketplace team. When I run `gradle runIde` on your branch of the source code (which is identical to 0.1.26), the stack trace can be observed too.

 
>> (From Jetbrains) The following error message occurs in the IDE with this plugin update. Please check on this: 

 ```
java.lang.Throwable: Do not use constructor injection (requestorClass=io.binx.cfnlint.plugin.CheckProjectComponent)
  at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
  at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:78)
  at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1041)
  at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:36)
  at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:154)
  at com.intellij.serviceContainer.BaseComponentAdapter.createInstance$lambda$1(BaseComponentAdapter.kt:133)
  at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
  at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:132)
  at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:19)
  at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:181)
  at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
  at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
  at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
  at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
  at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
  at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:176)
  at com.intellij.serviceContainer.ComponentManagerImpl.createComponentsNonBlocking(ComponentManagerImpl.kt:469)
  at com.intellij.openapi.project.impl.ProjectImpl.access$createComponentsNonBlocking(ProjectImpl.kt:57)
  at com.intellij.openapi.project.impl.ProjectImpl$Companion$preloadServicesAndCreateComponents$2.invokeSuspend(ProjectImpl.kt:103)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by zfil** [comment]
Ok I can reproduce too with runIde ...
So I guess I need to complete the upgrde sooner I expected!

What puzzles me is that using the packaged plugin works fine ...
Could you please try with the plugin I shared to let me know if it is specific to my machine ? That will help me :)

**Comment by mvanholsteijn** [comment]
Philippe,  the plugin indeed can be installed in the IDE and is operational 

Cheers,

Mark

**Pull request merged**
